version: "3"

services:
  web:
    build: ./app
    command: gunicorn thilos_website.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - /home/thilo/docker/thilos_server/volumes/wagtail/static:/app/static
      - /home/thilo/docker/thilos_server/volumes/wagtail/media:/app/media
      - ./backups:/app/backups
    env_file:
     - ./.env.prod
    networks:
      - service_connector
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - service_connector

volumes:
  postgres_data:

networks:
  service_connector:
    external:
      name: service_connector