# Generated by Django 3.1.8 on 2021-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='description',
            field=models.TextField(help_text='Write a description of the journey', null=True),
        ),
    ]
