# Generated by Django 3.1.8 on 2021-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_my_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='my_title',
            field=models.CharField(blank=True, default='Hello World', max_length=100, null=True, verbose_name='Test'),
        ),
    ]
