# Generated by Django 3.1.8 on 2021-05-03 20:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210503_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='my_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='business_description',
            field=wagtail.core.fields.RichTextField(default='Trust me I am an engineer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='privat_description',
            field=wagtail.core.fields.RichTextField(default='I like travelling'),
        ),
    ]
