# Generated by Django 3.1.8 on 2021-09-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0009_auto_20210917_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='author_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_text',
            field=models.TextField(help_text='Welcome text on the Home Page', max_length=100, null=True),
        ),
    ]
