# Generated by Django 3.1.8 on 2021-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210918_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image_caption',
            field=models.TextField(help_text='Welcome text on the Home Page', max_length=100, null=True),
        ),
    ]
