# Generated by Django 3.1.8 on 2021-09-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210918_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='author_picture',
        ),
    ]
