# Generated by Django 3.1.8 on 2021-05-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='my_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
