# Generated by Django 3.1.8 on 2021-09-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0011_homepage_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='author_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_caption',
            field=models.TextField(help_text='Caption below the image of the Author', max_length=100, null=True),
        ),
    ]
